# This is a basic workflow to help you get started with Actions

name: Pull Request SMS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: 46elks SMS
      uses: 46elks/gh-actions-sms@v1.0.2
      with:
        # Your 46elks API username.
        apiUsername: 
        # Your 46elks API password.
        apiPassword: 
        # The phone number to send an SMS to
        to: # default is +46700000000
        # The phone number or text sender id to send the SMS from
        from: # default is ElkAction
        # The message to send
        message: # default is Elky greetings from GitHub actions!
